os: osx
osx_image: xcode11.3
language: go
go:
  - 1.13.8
sudo: required
before_install:
  - docker version || true
  - ./hack/install_docker_on_travis.sh
  - docker version
  - docker info
install:
  - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64 && sudo install minikube-darwin-amd64 /usr/local/bin/minikube
script:
  - minikube start --driver=docker --alsologtostderr -v=8
  - docker ps
  - docker images
  - minikube status
